### ISSUE TITLE
Please add the focal_loss code

### ISSUE THREAD

**Issue by WangBJ233** [YazhouZhu19/PAMI#2]
![image](https://github.com/YazhouZhu19/PAMI/assets/59432372/69e250e3-287e-4ce5-926b-490719b4d4f4)
Hello author, thank you very much for your outstanding work. Your train.py file shows focal_loss, please add this loss code

**Comment by daqiudi** [comment]
> ![image](https://user-images.githubusercontent.com/59432372/269861326-69e250e3-287e-4ce5-926b-490719b4d4f4.png) Hello author, thank you very much for your outstanding work. Your train.py file shows focal_loss, please add this loss code

你解决了吗，我也是遇到一样的问题，请问你的focal loss装的是什么版本

**Comment by YazhouZhu19** [comment]
We didn't use focal loss in this paper
